CREATE TABLE DropOffZones(
    Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PhysicalAddress VARCHAR(255) NOT NULL,
    Latitude VARCHAR(50) NOT NULL,
    Longitude VARCHAR(50) NOT NULL,
    ContactName VARCHAR(255) NOT NULL,
    ContactNumber VARCHAR(50) NOT NULL,
    EmailAddress VARCHAR(255) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)