CREATE TABLE Users (
	[Id] INT IDENTITY PRIMARY KEY NOT NULL,
	[FirstName] VARCHAR(255) NOT NULL,
	[LastName] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NOT NULL UNIQUE,
	[UserName] VARCHAR(255) NOT NULL UNIQUE,
	[Salt] VARCHAR(255) NOT NULL,
	[HashedPassword] NVARCHAR(max) NOT NULL,
	[CreatedOn] DATE DEFAULT GETDATE(),
)